version: "3.9"
services:
  database:
    image: mysql:8.0
    restart: on-failure
    environment:
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=b446b342-608c-11ee-8c99-0242ac120002"
      - "MYSQL_DATABASE=contrnastyp"
      - "MYSQL_ROOT_PASSWORD=9631a2e4-608d-11ee-8c99-0242ac120002"
    volumes:
      - "./db/postgres:/var/lib/postgresql/data"
    networks:
      - general

  api:
    build: ./server
    restart: always
    volumes:
      - "./server:/code"
    networks:
      - general

  client:
    build: ./client
    volumes:
      - "./cliend:/code"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - "./api/build/:/etc/nginx/src/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/mime.type:/etc/nginx/mime.type"
    ports:
      - "${NGINX_EXTERNAL_PORT:-80}:80"
    networks:
      - general

networks:
  general:
    driver: bridge